name: Publish package
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'
          scope: '@myalbum'
      - name: Install
        run: yarn
      - name: Test
        run: yarn test
      - name: Eslint
        run: yarn run validate:eslint
      - name: Flow
        run: yarn run validate:flow
      - name: TypeScript
        run: yarn run validate:typescript
      - name: Jest
        run: yarn run test:jest
      - name: Android JavaScript Bundle
        run: yarn run test:detox:android:bundle:release
      - name: iOS JavaScript Bundle
        run: yarn run test:detox:ios:bundle:release
      - name: Release
        run: yarn ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
          NPM_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
