name: Publish package
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: yarn
      - name: Test
        run: yarn test
  publish:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'
          scope: '@myalbum'
      - name: Install
        run: yarn
      - name: Setup git
        run: |
          git config --local user.email "sysadmin@myalbum.com"
          git config --local user.name "MyAlbum System"
      - name: Release
        run: yarn ci:publish
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          tags: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
